# Generated by Django 4.0.5 on 2022-06-04 16:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(default='', verbose_name='Заметка')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('importance', models.BooleanField(default=False, verbose_name='Важность')),
                ('create_date', models.DateField(verbose_name='Время создания')),
                ('complete', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('complete_date', models.DateField(default=datetime.date(2022, 6, 5), verbose_name='Время выполнения')),
                ('status', models.CharField(choices=[('Активно', 'Active'), ('Отложено', 'Postpone'), ('Выполнено', 'Complete')], default='Активно', max_length=10, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
