# Generated by Django 4.0.5 on 2022-06-05 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='complete_date',
            field=models.DateField(default=datetime.date(2022, 6, 6), verbose_name='Время выполнения'),
        ),
    ]
