# Generated by Django 4.0.5 on 2022-06-05 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_complete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create_date',
            field=models.DateField(default=datetime.date(2022, 6, 5), verbose_name='Время создания'),
        ),
    ]
