# Generated by Django 4.0.5 on 2022-06-05 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='complete_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 6, 12, 34, 8, 158872, tzinfo=utc), verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='note',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 5, 12, 34, 8, 158872, tzinfo=utc), verbose_name='Время создания'),
        ),
    ]
