# Generated by Django 4.0.5 on 2022-06-05 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_complete_date_alter_note_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='complete_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 13, 0, 22, 887993, tzinfo=utc), verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='note',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 13, 0, 22, 887993, tzinfo=utc), verbose_name='Время создания'),
        ),
    ]
